apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-credentials
type: Opaque
data:
  database-username: {{ .Values.database.username | b64enc | quote }}
  database-password: {{ .Values.database.password | b64enc | quote }}
