apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-database-errors
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8088'
spec:
  containers:
    - name: database-errors
      image: database-errors:0.1.0
      ports:
        - containerPort: 8088
      env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-sql-scripts
              key: database-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-credentials
              key: database-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-credentials
              key: database-password
        - name: CRON_VAR
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-sql-scripts
              key: cron-var
      volumeMounts:
        - name: sql-scripts
          mountPath: /sql-scripts
  volumes:
    - name: sql-scripts
      configMap:
        name: {{ .Release.Name }}-sql-scripts
