apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sql-scripts
data:
  query1_errors.sql: |
    {{ .Values.sqlScripts.script1 | indent 4 }}
  query2_errors.sql: |
    {{ .Values.sqlScripts.script2 | indent 4 }}
  query3_errors.sql: |
    {{ .Values.sqlScripts.script3 | indent 4 }}
  query4_errors.sql: |
    {{ .Values.sqlScripts.script4 | indent 4 }}

  database-url: {{ .Values.database.url }}
  cron-var: {{ .Values.database.cronVar }}

